import React from 'react';

/**
 * Enum representing the supported marketplace platforms.
 */
export enum Platform {
  Ebay = 'Ebay',
  Facebook = 'Facebook',
  Craigslist = 'Craigslist',
  X = 'X',
}

/**
 * Defines the structure for platform-specific information, including its ID, name, and icon.
 */
export interface PlatformInfo {
  id: Platform;
  name: string;
  icon: React.ReactElement;
}

/**
 * Represents a single bin in the price distribution histogram.
 */
export interface PriceDistributionBin {
  /** The price range for the bin (e.g., "$180-$200"). */
  range: string;
  /** The number of comparable listings found within this price range. */
  count: number;
}

/**
 * Contains the detailed pricing analysis generated by the AI.
 */
export interface PriceAnalysis {
  /** A competitive price range for the item (e.g., "$200 - $250"). */
  range: string;
  /** A brief justification for the suggested price. */
  analysis: string;
  /** The AI's confidence level in its pricing analysis. */
  confidence: 'High' | 'Medium' | 'Low';
  /** The total number of comparable listings found. */
  comparableListingsCount: number;
  /** The average age in days of the active comparable listings. */
  averageListingAgeDays: number;
  /** An array of bins for a price distribution histogram. */
  priceDistribution: PriceDistributionBin[];
}

/**
 * Represents the complete listing object returned by the Gemini API.
 */
export interface GeneratedListing {
  /** The specific name of the item identified by the AI. */
  itemName: string;
  /** The detailed pricing analysis for the item. */
  suggestedPrice: PriceAnalysis;
  /** The generated title, description, and tags for the listing. */
  listing: {
    title: string;
    description: string;
    tags?: string[];
  };
}

/**
 * Represents a user-uploaded or camera-captured image file.
 */
export interface ImageFile {
  /** The base64-encoded string of the image data. */
  base64: string;
  /** The MIME type of the image (e.g., 'image/jpeg'). */
  mimeType: string;
  /** The original name of the image file. */
  name: string;
}

/**
 * A version of the generated listing specifically for the history,
 * allowing `suggestedPrice` to be a string for backward compatibility with older, stored data.
 */
export interface HistoryListing extends Omit<GeneratedListing, 'suggestedPrice'> {
    suggestedPrice: PriceAnalysis | string;
}

/**
 * Represents a single item in the user's generation history or saved listings.
 */
export interface HistoryItem {
  /** A unique identifier for the history item, typically a timestamp. */
  id: number;
  /** The platform the listing was generated for. */
  platform: Platform;
  /** The user's original input (text and/or image). */
  input: {
    text: string;
    image: ImageFile | null;
  };
  /** The AI-generated listing data. */
  listingData: HistoryListing;
  /** An ISO 8601 timestamp string of when the item was created. */
  timestamp: string;
  /** An optional, user-provided custom title for the listing. */
  customTitle?: string;
}

/**
 * Defines the structure for storing all user-provided API keys.
 */
export interface ApiKeys {
  ebay: string;
  x: string;
  gemini: string;
  openai: string;
}

/**
 * Represents a single data point for the price history chart.
 */
export interface PriceHistoryPoint {
  /** The date for the data point in 'YYYY-MM-DD' format. */
  date: string;
  /** The average price for that date. */
  price: number;
}